MONGODB_HOST: mongodb-{{ env }}.manidevops.fun # mongodb-dev.manidevops.fun
REDIS_HOST: redis-{{ env }}.manidevops.fun
CATALOGUE_HOST: catalogue-{{ env }}.manidevops.fun
CART_HOST: cart-{{ env }}.manidevops.fun
USER_HOST: user-{{ env }}.manidevops.fun
RABBITMQ_HOST: rabbitmq-{{ env }}.manidevops.fun
MYSQL_HOST: mysql-{{ env }}.manidevops.fun
SHIPPING_HOST: shipping-{{ env }}.manidevops.fun
PAYMENT_HOST: payment-{{ env }}.manidevops.fun